/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOBKG
#define ROOBKG

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class Bkg : public RooAbsPdf {
public:
  Bkg() {} ; 
  Bkg(const char *name, const char *title,
	      RooAbsReal& _m,
              RooAbsReal& _a1,
              RooAbsReal& _a2);
  Bkg(const Bkg& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Bkg(*this,newname); }
  inline virtual ~Bkg() { }

protected:

  RooRealProxy m ;
  RooRealProxy a1 ;
  RooRealProxy a2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(Bkg,1) // Your description goes here...
};
 
#endif
